# Generated by Django 6.0.6 on 2026-06-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="patient_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
